import React from 'react';

class AboutPage extends React.Component {
  render() {
    return (
      <div className="central">
        <h1>Lorem Ipsum:</h1>
        <p>Cu cîteva excepţii, n-am prizat încercările muzicienilor români de a  integra în opera lor teme venite din zona folclorică. Phoenix a reuşit,  acum mai bine de 30 de ani, să se apropie de idealul unui sunet care  n-avea cum să fie originat decît în spaţiul acesta, motivele sonore  cvasi-primitive fiind inteligent şi convingător topite în ceea ce muzica  îşi asuma atunci ca modernitate, rock-ul. Rock-ul, invenţia nemesisului  din Vest. O încercase şi Sincron-ul lui Cornel Fugaru, dar acolo era  vorba doar de o altfel de interpretare a pieselor din folclor,  construite pur şi simplu surf rock-ist. Pe undeva, şi Sfinx reuşise să  adulmece urma monstrului arhetipar, pe Zamolxe , însă era acolo  un apel la mitologie & folclor în numele unei psihedelii naţionale.  Savoy încercase şi ea marea cu degetul. N-a fost să fie, pentru că anii  ’80 au rezolvat problema iluziei libertăţii cu voie de sus, iar regimul  acela şi-a creat propria variantă de folclor modernizat, unul în care  industria metalurgică înlocuise tablourile cîmpeneşti. Toate proiectele  de gen care au urmat, la o distanţă în timp considerabilă, s-au împărţit  injust între acceptabil şi greţos. În 2010, lucrurile parcă stau un pic  altfel. </p>
        <p>Bean, aşa cum mai e cunoscut autorul albumului despre care scriu  aici, membru al colectivului Blanoz şi actual vocalist al trupei Şuie  Paparude, trecut pentru o vreme şi prin L’Orchestre de Roche, face parte  dintr-o generaţie cu dublă moştenire, care a crescut cu televizorul  etern comutat pe toate MTV-urile ultimilor 20 de ani şi cu  calculatoarele mereu conectate la toate sursele www ale ultimilor 10,  „pe la Romană“, în centrul unei urbanităţi a cărei sete de importuri  culturale vestice nu s-a potolit niciodată, dar şi „prin Dolhasca, la  cîmpie“, spaţiul în care arhaismele (şi derivatele lor) încă mai sînt  conservate şi performate. E declaraţia de intenţie pe care o face pe „Am  crescut pe la Romană“, o strigătură în care tempoul infernal al kick-urilor  maramureşene se varsă destul de logic în drum&bass. Forma în care  artistul toarnă esenţe din folclor e una surprinzătoare pentru  genul/genurile muzical/e pe care le cultivă şi pentru muzica românească,  în general.</p>
        <p>Încercarea de reîntoarcere la rădăcini, la copilărie – a lui, dar şi a  muzicii – este una sinceră, chit că mobilul ar putea să fie o  originalitate pe care n-ai cum s-o obţii altfel astăzi, în momentul în  care totul pare a fi fost deja spus în muzică, în care fast-food pop-ul  vestic e bine fixat în reflexul unui anumit tip de producător şi  consumator. La fel de bine cum poate fi o dorinţă a autorului de a-şi  recupera, revizita şi asimila trecutul, de a-şi rezolva o problemă mai  degrabă abisală (vezi aluzia la muzica pe care o ascultau bunicii lui),  de a se maturiza, pînă la urmă. Bean/Subcarpaţi şi-a găsit sursa noii  energii şi ne spune şi nouă secretul pe „Doina spiritului“, unul dintre  punctele tari ale albumului (alături de „Salvez lumea“, „Hora  fericirii“, „La cutari“, tripantul featuring aromân al Marei,  sau „Atît de personal“). Mai mult, mută doina în contemporaneitate,  adoptînd – iată o inovaţie! – modelul vocal al lăutarului de altădată.  „Cînd a fost la ’89“ decupează şi folclorizează cu stil o perioadă la  care memoria colectivă tresare, pe tiparul aceloraşi vechi interpreţi,  cei care înregistrau şi reproduceau un anumit moment istoric. Repetiţia  unor sample-uri populare/lăutăreşti livrează albumului o  atmosferă stranie şi o febrilitate foarte viscerală. Şi chiar dacă  idiomul nu e absorbit întotdeauna complet – poate de aici vine uneori  aerul de improvizaţie, de construcţie cumva şubredă –, rezultatul final  conciliază lăudabil muzicile vechi cu cele noi, sîrbele cu trip-hop-ul,  doinele cu hip-hop-ul, horele cu dubstep-ul… </p>
      </div>
    );
  }
}

export default AboutPage;
